package aec2.metro.implementacion.undergroundapp;

import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;

public class DeleteStationWindow extends ConnectionWindow {

	/* autogenerated serailVersionUID*/
	private static final long serialVersionUID = -2977244584550916138L;

	
	public DeleteStationWindow(String[] infoStations,String name) {
		
		super();
		this.setTitle(name);
		this.initComponents(infoStations);
		this.setModal(true);
		this.setPreferredSize(new Dimension(300,200));
		this.setResizable(false);
		this.pack();
		this.setLocationRelativeTo(null);
		this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
		
		
	}
	
	@Override
	protected void initComponents(String[] infoStations) {
		
		
		GridBagConstraints gridConstraints = new GridBagConstraints();
		this.setLayout(new GridBagLayout());
		gridConstraints.insets=new Insets(5,1,1,1);
		//labels
		 lOrigin= new JLabel("Station: ");
		 gridConstraints.gridx= 0;
		 gridConstraints.gridy=0;
		 this.add(lOrigin);
		 
		 
		 
		 //JComboBox
		comboBoxOrigin= new JComboBox<String>(infoStations);
		comboBoxOrigin.setSize(100, 20);
		comboBoxOrigin.setEditable(false);
		gridConstraints.gridx=1;
		gridConstraints.gridy=0;
		gridConstraints.gridwidth=3;
		gridConstraints.fill= GridBagConstraints.HORIZONTAL;
		this.add(comboBoxOrigin,gridConstraints);

		
		
		//JButton
		acceptConnectionButton= new JButton("Aceptar");
		gridConstraints.gridx=1;
	    gridConstraints.gridy=1;
	    this.add(acceptConnectionButton,gridConstraints);
		
		
	}
	
	
	
	
	
	
	
	
	
	
	
	
	
}
